-d C:\Users\danilo\Documents\Hello World\impl\gwsynthesis\Hello World.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst C:\Users\danilo\Documents\Hello World\src\pin.cst
-cfg C:\Users\danilo\Documents\Hello World\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
